apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: html-pv0
    labels:
        name: html-pv0
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
    name: html-pod-pv0
    labels:
        env: testing
        region: IN
        app: html
spec:
    containers:
    - name: myhtml-con
      image: vimal13/apache-webserver
      volumeMounts:
      - name: html-vol
        mountPath: /var/www/html
    volumes:
    - name: html-vol
      persistentVolumeClaim:
        claimName: html-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: html-svc0
  labels:
    app: html
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30002
    port: 81
    targetPort: 80
  selector:
    app: html
---
